apiVersion: v1
kind: Pod
metadata:
  name: ratls-proxy
spec:
  runtimeClassName: gvisor
  containers:
  - name: ratls-proxy
    image: docker.io/library/ratls:786beb0ea21749ae8b9f03d502f44dd31f3e43b1f15ee1abb827a936838d6ada
    ports:
    - containerPort: 8080
